let daten2021 = [
  { land: "Deutschland", unternehmen: "Volkswagen AG", emission: 8234567 },
  { land: "USA", unternehmen: "ExxonMobil", emission: 7456321 },
  { land: "China", unternehmen: "China National Petroleum", emission: 9123456 },
  { land: "Japan", unternehmen: "Toyota Motor Corporation", emission: 6342789 },
  { land: "Indien", unternehmen: "Reliance Industries", emission: 5234671 },
  { land: "Russland", unternehmen: "Gazprom", emission: 8543271 },
  { land: "Brasilien", unternehmen: "Petrobras", emission: 7845123 },
  { land: "Kanada", unternehmen: "Suncor Energy", emission: 6923481 },
  { land: "Frankreich", unternehmen: "TotalEnergies", emission: 6127345 },
  { land: "Vereinigtes Königreich", unternehmen: "BP", emission: 7451263 },
  { land: "Südafrika", unternehmen: "Sasol", emission: 5678234 },
  { land: "Italien", unternehmen: "Eni", emission: 6347892 },
  { land: "Australien", unternehmen: "BHP Group", emission: 6789123 },
  { land: "Südkorea", unternehmen: "Hyundai Motor Company", emission: 7234815 },
  { land: "Mexiko", unternehmen: "Pemex", emission: 8012345 },
  { land: "Saudi-Arabien", unternehmen: "Saudi Aramco", emission: 9348123 },
  { land: "Spanien", unternehmen: "Repsol", emission: 5789241 },
  { land: "Schweden", unternehmen: "Volvo Group", emission: 4321876 },
  { land: "Norwegen", unternehmen: "Equinor", emission: 4918273 },
  { land: "Niederlande", unternehmen: "Royal Dutch Shell", emission: 8457321 },
  { land: "Finnland", unternehmen: "Neste", emission: 3678924 },
  { land: "Österreich", unternehmen: "OMV", emission: 4789213 },
  { land: "Argentinien", unternehmen: "YPF", emission: 5234768 },
  { land: "Indonesien", unternehmen: "Pertamina", emission: 6348921 },
  { land: "Malaysia", unternehmen: "Petronas", emission: 7582394 },
  { land: "Thailand", unternehmen: "PTT Group", emission: 5921348 },
  { land: "Schweiz", unternehmen: "Glencore", emission: 4785632 },
  { land: "Singapur", unternehmen: "Singapore Airlines", emission: 3918457 },
  { land: "Ägypten", unternehmen: "EGPC", emission: 6123745 },
  { land: "Türkei", unternehmen: "Tüpraş", emission: 7431892 },
];
let daten2022 = [
  { land: "Polen", unternehmen: "PKN Orlen", emission: 6732184 },
  { land: "Tschechien", unternehmen: "ČEZ Group", emission: 5213786 },
  { land: "Portugal", unternehmen: "Galp Energia", emission: 4987213 },
  { land: "Ungarn", unternehmen: "MOL Group", emission: 6148937 },
  {
    land: "Griechenland",
    unternehmen: "Hellenic Petroleum",
    emission: 5372169,
  },
  { land: "Ukraine", unternehmen: "Naftogaz", emission: 7194825 },
  {
    land: "Israel",
    unternehmen: "Israel Electric Corporation",
    emission: 4827139,
  },
  { land: "Irland", unternehmen: "CRH plc", emission: 3574918 },
  { land: "Dänemark", unternehmen: "Ørsted", emission: 2984761 },
  { land: "Belgien", unternehmen: "Solvay", emission: 4127356 },
  { land: "Chile", unternehmen: "Codelco", emission: 4981237 },
  { land: "Kolumbien", unternehmen: "Ecopetrol", emission: 5739182 },
  { land: "Venezuela", unternehmen: "PDVSA", emission: 8943127 },
  { land: "Peru", unternehmen: "Petroperú", emission: 6782913 },
  { land: "Kroatien", unternehmen: "INA Group", emission: 4912738 },
  { land: "Serbien", unternehmen: "NIS", emission: 5371942 },
  { land: "Bulgarien", unternehmen: "Lukoil Bulgaria", emission: 4158932 },
  { land: "Rumänien", unternehmen: "OMV Petrom", emission: 5738921 },
  { land: "Slowakei", unternehmen: "Slovnaft", emission: 6981245 },
  { land: "Kasachstan", unternehmen: "KazMunayGas", emission: 8174936 },
  { land: "Usbekistan", unternehmen: "Uzbekneftegaz", emission: 4917382 },
  { land: "Aserbaidschan", unternehmen: "SOCAR", emission: 6471823 },
  { land: "Vietnam", unternehmen: "PetroVietnam", emission: 5123847 },
  {
    land: "Philippinen",
    unternehmen: "San Miguel Corporation",
    emission: 4893725,
  },
  { land: "Bangladesch", unternehmen: "Petrobangla", emission: 3178942 },
  { land: "Pakistan", unternehmen: "OGDCL", emission: 4352187 },
  {
    land: "Iran",
    unternehmen: "National Iranian Oil Company",
    emission: 9238147,
  },
  { land: "Irak", unternehmen: "North Oil Company", emission: 7984123 },
  {
    land: "Kuwait",
    unternehmen: "Kuwait Petroleum Corporation",
    emission: 7128345,
  },
  {
    land: "Vereinigte Arabische Emirate",
    unternehmen: "ADNOC",
    emission: 8342917,
  },
];
let daten2023 = [
  { land: "Neuseeland", unternehmen: "Contact Energy", emission: 3192847 },
  { land: "Fidschi", unternehmen: "Energy Fiji Limited", emission: 1847329 },
  { land: "Papua-Neuguinea", unternehmen: "PNG Power", emission: 2938471 },
  { land: "Samoa", unternehmen: "EPC Samoa", emission: 1329471 },
  { land: "Tonga", unternehmen: "Tonga Power Limited", emission: 1139247 },
  { land: "Vanuatu", unternehmen: "UNELCO Vanuatu", emission: 1294837 },
  { land: "Salomonen", unternehmen: "Solomon Power", emission: 1948273 },
  { land: "Kiribati", unternehmen: "PUB Kiribati", emission: 984132 },
  {
    land: "Marshallinseln",
    unternehmen: "Marshalls Energy Company",
    emission: 1348972,
  },
  {
    land: "Nauru",
    unternehmen: "NAURU Utilities Corporation",
    emission: 918345,
  },
  {
    land: "Tuvalu",
    unternehmen: "Tuvalu Electricity Corporation",
    emission: 829174,
  },
  {
    land: "Palau",
    unternehmen: "Palau Public Utilities Corporation",
    emission: 1347985,
  },
  { land: "Mikronesien", unternehmen: "FSMPC", emission: 1934875 },
  { land: "Australien", unternehmen: "Rio Tinto", emission: 6183947 },
  { land: "Kanada", unternehmen: "Teck Resources", emission: 5981347 },
  { land: "USA", unternehmen: "Chevron", emission: 8173924 },
  { land: "Mexiko", unternehmen: "Cemex", emission: 4812376 },
  { land: "Chile", unternehmen: "Antofagasta PLC", emission: 5183924 },
  { land: "Argentinien", unternehmen: "Techint", emission: 3948721 },
  { land: "Brasilien", unternehmen: "Vale S.A.", emission: 7891342 },
  { land: "Kolumbien", unternehmen: "Argos", emission: 4178239 },
  { land: "Venezuela", unternehmen: "CANTV", emission: 2879341 },
  {
    land: "Peru",
    unternehmen: "Southern Copper Corporation",
    emission: 5981273,
  },
  { land: "Bolivien", unternehmen: "YPFB", emission: 4739217 },
  { land: "Paraguay", unternehmen: "ANDE", emission: 2948173 },
  { land: "Uruguay", unternehmen: "UTE", emission: 1839471 },
  { land: "Ecuador", unternehmen: "Petroamazonas", emission: 4781239 },
  { land: "Suriname", unternehmen: "Staatsolie", emission: 3284719 },
  { land: "Guyana", unternehmen: "Esso Guyana", emission: 2138476 },
  { land: "Französisch-Guayana", unternehmen: "EDF", emission: 1348279 },
];
let daten2024 = [
  { land: "Nigeria", unternehmen: "NNPC", emission: 8293471 },
  { land: "Angola", unternehmen: "Sonangol", emission: 6723841 },
  { land: "Algerien", unternehmen: "Sonatrach", emission: 7914832 },
  { land: "Marokko", unternehmen: "OCP Group", emission: 4823917 },
  {
    land: "Kenia",
    unternehmen: "Kenya Electricity Generating Company",
    emission: 3412795,
  },
  {
    land: "Äthiopien",
    unternehmen: "Ethiopian Electric Power",
    emission: 2734891,
  },
  { land: "Tansania", unternehmen: "Tanesco", emission: 3851729 },
  {
    land: "Uganda",
    unternehmen: "Uganda National Oil Company",
    emission: 2183946,
  },
  { land: "Sambia", unternehmen: "ZESCO", emission: 1948375 },
  { land: "Simbabwe", unternehmen: "ZESA Holdings", emission: 2763819 },
  {
    land: "Ghana",
    unternehmen: "Ghana National Petroleum Corporation",
    emission: 4178923,
  },
  { land: "Elfenbeinküste", unternehmen: "CIE", emission: 3172849 },
  { land: "Senegal", unternehmen: "Petrosen", emission: 2947185 },
  { land: "Kamerun", unternehmen: "SNH", emission: 3548712 },
  { land: "Südafrika", unternehmen: "Eskom", emission: 8973124 },
  { land: "Malawi", unternehmen: "EGENCO", emission: 2189731 },
  { land: "Mosambik", unternehmen: "EDM", emission: 3571248 },
  { land: "Namibia", unternehmen: "NamPower", emission: 2817945 },
  {
    land: "Botswana",
    unternehmen: "Botswana Power Corporation",
    emission: 3284917,
  },
  { land: "Madagaskar", unternehmen: "Jirama", emission: 1947382 },
  { land: "Tunesien", unternehmen: "STEG", emission: 3718924 },
  {
    land: "Libyen",
    unternehmen: "National Oil Corporation",
    emission: 7982134,
  },
  { land: "Sudan", unternehmen: "Sudapet", emission: 4918273 },
  {
    land: "Somalia",
    unternehmen: "Somali Petroleum Corporation",
    emission: 2183947,
  },
  { land: "Tschad", unternehmen: "SHT", emission: 3871925 },
  { land: "Mali", unternehmen: "EDM SA", emission: 1942837 },
  { land: "Niger", unternehmen: "SOPAMIN", emission: 2183497 },
  { land: "Mauritius", unternehmen: "CEB", emission: 1853741 },
  { land: "Seychellen", unternehmen: "PUC", emission: 1398472 },
  { land: "Dschibuti", unternehmen: "EDD", emission: 2183945 },
];
